### ISSUE TITLE
Where is file train_XYZ.py?

### ISSUE THREAD

**Issue by Ulitochka** [mpsilfve/pcfp-data#1]
Hello.

Thank you for your work. 

But where is train_XYZ.py file?

**Comment by mpsilfve** [comment]
Hi,

Thanks for your interest! :)

The task is to fill in the missing forms in partial inflection tables. You do not get to observe any complete tables during training. You only see the incomplete tables. You should learn a model based on the incomplete data and use it to fill in the missing forms.

In practice, your system should take all of the files LAN.um.POS.NUM.txt as input. The result is evaluated w.r.t. to files LAN.um.POS.txt. 

In a separate experiment, your system should take the tables LAN.um.POS.top.10000.txt as input and complete those. Again, the result is evaluated w.r.t. LAN.um.POS.txt.

Did this answer your question?

**Comment by Ulitochka** [comment]
Thanks!
